name: ${project.name}
version: ${project.version}
description: ${project.description}
author: noogotte
website: https://github.com/noogotte/PvPHeadDrop

main: fr.noogotte.pvpheaddrop.PvPHeadDrop

# Permissions
permissions:
    pvphead.drop:
        default: true
    pvphead.receive:
        default: true
